import { roleValidator } from "../betterAuth/schema";
import type { Category } from "./types";

export const Owner = roleValidator.members[0];
export const Member = roleValidator.members[1];

export const MAX_FILE_SIZE = 1 * 1024 * 1024;

export const LIMITS = {
    MAX_REQUESTS_PER_USER: 100,
    MAX_TRIPS_PER_USER: 50,
};

export const VALID_CATEGORIES: Category[] = [
    "food",
    "activity",
    "transport",
    "accommodation",
    "shopping",
    "other",
];

export const BLOCKED_WORDS = [
    "bc",
    "b.c",
    "b c",
    "mc",
    "m.c",
    "m c",
    "bkl",
    "bklol",
    "chutiya",
    "chutia",
    "chutya",
    "chut",
    "chutiye",
    "chutiyapa",
    "lodu",
    "loda",
    "lode",
    "lodu",
    "gandu",
    "gand",
    "gaand",
    "gandmara",
    "gaandmara",
    "lund",
    "loda",
    "lodu",
    "bhosdi",
    "bhosdike",
    "bhosdika",
    "bhosda",
    "bhenchod",
    "behenchod",
    "behen ch*d",
    "bhench*d",
    "madarchod",
    "maderchod",
    "madar ch*d",
    "madarch*d",
    "randi",
    "rand",
    "randiya",
    "harami",
    "haraami",
    "kamine",
    "kamina",
    "kameena",
    "kutte",
    "kutta",
    "saale",
    "sale",
    "chakka",
    "bakchod",
    "bakchodi",
    "jhatu",
    "jhant",
    "jhaant",
    "jhand",
    "jhantu",
    "tatti",
    "tati",
    "haggu",
    "hagna",
    "mut",
    "mutna",
    "gaandfat",
    "gandfat",
    "lavda",
    "lawda",
    "lauda",
    "launda",
    "lulli",
    "loda",
    "chichora",
    "ullu ka pattha",
    "ullu ke pathe",
    "kuttiya",
    "kutiya",
    "bevakoof",
    "bewakoof",
    "bewkuf",
    "pagal",
    "paagal",
    "charsi",
    "nashedi",
    "suar",
    "suwar",
    "kutta",
    "kutti",
    "maal",
    "rakhail",
    "fuck",
    "fck",
    "fuk",
    "f*ck",
    "shit",
    "sh1t",
    "sh!t",
    "bitch",
    "b!tch",
    "asshole",
    "a$$hole",
    "bastard",
    "dick",
    "d1ck",
    "pussy",
    "slut",
    "whore",
    "motherfucker",
    "mf",
    "retard",
    "madarchod",
    "madrchod",
    "mdrchd",
    "behenchod",
    "bhnchod",
    "bhnchd",
    "chutiya",
    "chutya",
    "chtia",
    "gandu",
    "gndu",
    "lavda",
    "lvda",
    "bhosdike",
    "bhsdke",
];
