/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as homeTripsRouteImport } from './routes/(home)/trips'
import { Route as homeSettingsRouteImport } from './routes/(home)/settings'
import { Route as homeExpensesRouteImport } from './routes/(home)/expenses'
import { Route as homeDashboardRouteImport } from './routes/(home)/dashboard'
import { Route as homeBlogsRouteImport } from './routes/(home)/blogs'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authSignUpCreateUsernameRouteImport } from './routes/(auth)/sign-up/create-username'
import { Route as authSignUpCreateAccountRouteImport } from './routes/(auth)/sign-up/create-account'
import { Route as customTripsTripIdRouteRouteImport } from './routes/(custom)/trips/$tripId/route'
import { Route as customTripsTripIdInfoRouteImport } from './routes/(custom)/trips/$tripId/info'
import { Route as customTripsTripIdExpensesRouteImport } from './routes/(custom)/trips/$tripId/expenses'
import { Route as customTripsTripIdChatRouteImport } from './routes/(custom)/trips/$tripId/chat'
import { Route as customBlogsBlogIdBlogRouteImport } from './routes/(custom)/blogs/$blogId/blog'
import { Route as customBlogsBlogIdLayoutRouteImport } from './routes/(custom)/blogs/$blogId/_layout'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeTripsRoute = homeTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeSettingsRoute = homeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeExpensesRoute = homeExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeDashboardRoute = homeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeBlogsRoute = homeBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => homeRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpCreateUsernameRoute =
  authSignUpCreateUsernameRouteImport.update({
    id: '/(auth)/sign-up/create-username',
    path: '/sign-up/create-username',
    getParentRoute: () => rootRouteImport,
  } as any)
const authSignUpCreateAccountRoute = authSignUpCreateAccountRouteImport.update({
  id: '/(auth)/sign-up/create-account',
  path: '/sign-up/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const customTripsTripIdRouteRoute = customTripsTripIdRouteRouteImport.update({
  id: '/(custom)/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const customTripsTripIdInfoRoute = customTripsTripIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => customTripsTripIdRouteRoute,
} as any)
const customTripsTripIdExpensesRoute =
  customTripsTripIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => customTripsTripIdRouteRoute,
  } as any)
const customTripsTripIdChatRoute = customTripsTripIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => customTripsTripIdRouteRoute,
} as any)
const customBlogsBlogIdBlogRoute = customBlogsBlogIdBlogRouteImport.update({
  id: '/(custom)/blogs/$blogId/blog',
  path: '/blogs/$blogId/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const customBlogsBlogIdLayoutRoute = customBlogsBlogIdLayoutRouteImport.update({
  id: '/(custom)/blogs/$blogId/_layout',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof authSigninRoute
  '/blogs': typeof homeBlogsRoute
  '/dashboard': typeof homeDashboardRoute
  '/expenses': typeof homeExpensesRoute
  '/settings': typeof homeSettingsRoute
  '/trips': typeof homeTripsRoute
  '/trips/$tripId': typeof customTripsTripIdRouteRouteWithChildren
  '/sign-up/create-account': typeof authSignUpCreateAccountRoute
  '/sign-up/create-username': typeof authSignUpCreateUsernameRoute
  '/blogs/$blogId': typeof customBlogsBlogIdLayoutRoute
  '/blogs/$blogId/blog': typeof customBlogsBlogIdBlogRoute
  '/trips/$tripId/chat': typeof customTripsTripIdChatRoute
  '/trips/$tripId/expenses': typeof customTripsTripIdExpensesRoute
  '/trips/$tripId/info': typeof customTripsTripIdInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof authSigninRoute
  '/blogs': typeof homeBlogsRoute
  '/dashboard': typeof homeDashboardRoute
  '/expenses': typeof homeExpensesRoute
  '/settings': typeof homeSettingsRoute
  '/trips': typeof homeTripsRoute
  '/trips/$tripId': typeof customTripsTripIdRouteRouteWithChildren
  '/sign-up/create-account': typeof authSignUpCreateAccountRoute
  '/sign-up/create-username': typeof authSignUpCreateUsernameRoute
  '/blogs/$blogId': typeof customBlogsBlogIdLayoutRoute
  '/blogs/$blogId/blog': typeof customBlogsBlogIdBlogRoute
  '/trips/$tripId/chat': typeof customTripsTripIdChatRoute
  '/trips/$tripId/expenses': typeof customTripsTripIdExpensesRoute
  '/trips/$tripId/info': typeof customTripsTripIdInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(home)': typeof homeRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(home)/blogs': typeof homeBlogsRoute
  '/(home)/dashboard': typeof homeDashboardRoute
  '/(home)/expenses': typeof homeExpensesRoute
  '/(home)/settings': typeof homeSettingsRoute
  '/(home)/trips': typeof homeTripsRoute
  '/(custom)/trips/$tripId': typeof customTripsTripIdRouteRouteWithChildren
  '/(auth)/sign-up/create-account': typeof authSignUpCreateAccountRoute
  '/(auth)/sign-up/create-username': typeof authSignUpCreateUsernameRoute
  '/(custom)/blogs/$blogId/_layout': typeof customBlogsBlogIdLayoutRoute
  '/(custom)/blogs/$blogId/blog': typeof customBlogsBlogIdBlogRoute
  '/(custom)/trips/$tripId/chat': typeof customTripsTripIdChatRoute
  '/(custom)/trips/$tripId/expenses': typeof customTripsTripIdExpensesRoute
  '/(custom)/trips/$tripId/info': typeof customTripsTripIdInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/blogs'
    | '/dashboard'
    | '/expenses'
    | '/settings'
    | '/trips'
    | '/trips/$tripId'
    | '/sign-up/create-account'
    | '/sign-up/create-username'
    | '/blogs/$blogId'
    | '/blogs/$blogId/blog'
    | '/trips/$tripId/chat'
    | '/trips/$tripId/expenses'
    | '/trips/$tripId/info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/blogs'
    | '/dashboard'
    | '/expenses'
    | '/settings'
    | '/trips'
    | '/trips/$tripId'
    | '/sign-up/create-account'
    | '/sign-up/create-username'
    | '/blogs/$blogId'
    | '/blogs/$blogId/blog'
    | '/trips/$tripId/chat'
    | '/trips/$tripId/expenses'
    | '/trips/$tripId/info'
  id:
    | '__root__'
    | '/'
    | '/(home)'
    | '/onboarding'
    | '/(auth)/signin'
    | '/(home)/blogs'
    | '/(home)/dashboard'
    | '/(home)/expenses'
    | '/(home)/settings'
    | '/(home)/trips'
    | '/(custom)/trips/$tripId'
    | '/(auth)/sign-up/create-account'
    | '/(auth)/sign-up/create-username'
    | '/(custom)/blogs/$blogId/_layout'
    | '/(custom)/blogs/$blogId/blog'
    | '/(custom)/trips/$tripId/chat'
    | '/(custom)/trips/$tripId/expenses'
    | '/(custom)/trips/$tripId/info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  homeRouteRoute: typeof homeRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  authSigninRoute: typeof authSigninRoute
  customTripsTripIdRouteRoute: typeof customTripsTripIdRouteRouteWithChildren
  authSignUpCreateAccountRoute: typeof authSignUpCreateAccountRoute
  authSignUpCreateUsernameRoute: typeof authSignUpCreateUsernameRoute
  customBlogsBlogIdLayoutRoute: typeof customBlogsBlogIdLayoutRoute
  customBlogsBlogIdBlogRoute: typeof customBlogsBlogIdBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/trips': {
      id: '/(home)/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof homeTripsRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/settings': {
      id: '/(home)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof homeSettingsRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/expenses': {
      id: '/(home)/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof homeExpensesRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/dashboard': {
      id: '/(home)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof homeDashboardRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/blogs': {
      id: '/(home)/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof homeBlogsRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up/create-username': {
      id: '/(auth)/sign-up/create-username'
      path: '/sign-up/create-username'
      fullPath: '/sign-up/create-username'
      preLoaderRoute: typeof authSignUpCreateUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up/create-account': {
      id: '/(auth)/sign-up/create-account'
      path: '/sign-up/create-account'
      fullPath: '/sign-up/create-account'
      preLoaderRoute: typeof authSignUpCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(custom)/trips/$tripId': {
      id: '/(custom)/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof customTripsTripIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(custom)/trips/$tripId/info': {
      id: '/(custom)/trips/$tripId/info'
      path: '/info'
      fullPath: '/trips/$tripId/info'
      preLoaderRoute: typeof customTripsTripIdInfoRouteImport
      parentRoute: typeof customTripsTripIdRouteRoute
    }
    '/(custom)/trips/$tripId/expenses': {
      id: '/(custom)/trips/$tripId/expenses'
      path: '/expenses'
      fullPath: '/trips/$tripId/expenses'
      preLoaderRoute: typeof customTripsTripIdExpensesRouteImport
      parentRoute: typeof customTripsTripIdRouteRoute
    }
    '/(custom)/trips/$tripId/chat': {
      id: '/(custom)/trips/$tripId/chat'
      path: '/chat'
      fullPath: '/trips/$tripId/chat'
      preLoaderRoute: typeof customTripsTripIdChatRouteImport
      parentRoute: typeof customTripsTripIdRouteRoute
    }
    '/(custom)/blogs/$blogId/blog': {
      id: '/(custom)/blogs/$blogId/blog'
      path: '/blogs/$blogId/blog'
      fullPath: '/blogs/$blogId/blog'
      preLoaderRoute: typeof customBlogsBlogIdBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(custom)/blogs/$blogId/_layout': {
      id: '/(custom)/blogs/$blogId/_layout'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof customBlogsBlogIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface homeRouteRouteChildren {
  homeBlogsRoute: typeof homeBlogsRoute
  homeDashboardRoute: typeof homeDashboardRoute
  homeExpensesRoute: typeof homeExpensesRoute
  homeSettingsRoute: typeof homeSettingsRoute
  homeTripsRoute: typeof homeTripsRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeBlogsRoute: homeBlogsRoute,
  homeDashboardRoute: homeDashboardRoute,
  homeExpensesRoute: homeExpensesRoute,
  homeSettingsRoute: homeSettingsRoute,
  homeTripsRoute: homeTripsRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface customTripsTripIdRouteRouteChildren {
  customTripsTripIdChatRoute: typeof customTripsTripIdChatRoute
  customTripsTripIdExpensesRoute: typeof customTripsTripIdExpensesRoute
  customTripsTripIdInfoRoute: typeof customTripsTripIdInfoRoute
}

const customTripsTripIdRouteRouteChildren: customTripsTripIdRouteRouteChildren =
  {
    customTripsTripIdChatRoute: customTripsTripIdChatRoute,
    customTripsTripIdExpensesRoute: customTripsTripIdExpensesRoute,
    customTripsTripIdInfoRoute: customTripsTripIdInfoRoute,
  }

const customTripsTripIdRouteRouteWithChildren =
  customTripsTripIdRouteRoute._addFileChildren(
    customTripsTripIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  homeRouteRoute: homeRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  authSigninRoute: authSigninRoute,
  customTripsTripIdRouteRoute: customTripsTripIdRouteRouteWithChildren,
  authSignUpCreateAccountRoute: authSignUpCreateAccountRoute,
  authSignUpCreateUsernameRoute: authSignUpCreateUsernameRoute,
  customBlogsBlogIdLayoutRoute: customBlogsBlogIdLayoutRoute,
  customBlogsBlogIdBlogRoute: customBlogsBlogIdBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
