/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as layoutRouteRouteImport } from './routes/(layout)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as layouthomeRouteRouteImport } from './routes/(layout)/(home)/route'
import { Route as layouthomeTripsRouteImport } from './routes/(layout)/(home)/trips'
import { Route as layouthomeSettingsRouteImport } from './routes/(layout)/(home)/settings'
import { Route as layouthomeExpensesRouteImport } from './routes/(layout)/(home)/expenses'
import { Route as layouthomeDashboardRouteImport } from './routes/(layout)/(home)/dashboard'
import { Route as layouthomeBlogsRouteImport } from './routes/(layout)/(home)/blogs'
import { Route as authSignUpCreateUsernameRouteImport } from './routes/(auth)/sign-up/create-username'
import { Route as authSignUpCreateAccountRouteImport } from './routes/(auth)/sign-up/create-account'
import { Route as layoutcustomTripsTripIdRouteRouteImport } from './routes/(layout)/(custom)/trips/$tripId/route'
import { Route as layoutcustomPublicTripIdRouteRouteImport } from './routes/(layout)/(custom)/public/$tripId/route'
import { Route as layoutcustomBlogsBlogIdRouteRouteImport } from './routes/(layout)/(custom)/blogs/$blogId/route'
import { Route as layoutcustomPublicTripIdIndexRouteImport } from './routes/(layout)/(custom)/public/$tripId/index'
import { Route as layoutcustomBlogsBlogIdIndexRouteImport } from './routes/(layout)/(custom)/blogs/$blogId/index'
import { Route as layoutcustomTripsTripIdPlanRouteImport } from './routes/(layout)/(custom)/trips/$tripId/plan'
import { Route as layoutcustomTripsTripIdInfoRouteImport } from './routes/(layout)/(custom)/trips/$tripId/info'
import { Route as layoutcustomTripsTripIdExpensesRouteImport } from './routes/(layout)/(custom)/trips/$tripId/expenses'
import { Route as layoutcustomTripsTripIdChatRouteImport } from './routes/(layout)/(custom)/trips/$tripId/chat'
import { Route as layoutcustomBlogsBlogIdEditRouteImport } from './routes/(layout)/(custom)/blogs/$blogId/edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutRouteRoute = layoutRouteRouteImport.update({
  id: '/(layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const layouthomeRouteRoute = layouthomeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layouthomeTripsRoute = layouthomeTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => layouthomeRouteRoute,
} as any)
const layouthomeSettingsRoute = layouthomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => layouthomeRouteRoute,
} as any)
const layouthomeExpensesRoute = layouthomeExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => layouthomeRouteRoute,
} as any)
const layouthomeDashboardRoute = layouthomeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => layouthomeRouteRoute,
} as any)
const layouthomeBlogsRoute = layouthomeBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => layouthomeRouteRoute,
} as any)
const authSignUpCreateUsernameRoute =
  authSignUpCreateUsernameRouteImport.update({
    id: '/(auth)/sign-up/create-username',
    path: '/sign-up/create-username',
    getParentRoute: () => rootRouteImport,
  } as any)
const authSignUpCreateAccountRoute = authSignUpCreateAccountRouteImport.update({
  id: '/(auth)/sign-up/create-account',
  path: '/sign-up/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutcustomTripsTripIdRouteRoute =
  layoutcustomTripsTripIdRouteRouteImport.update({
    id: '/(custom)/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutcustomPublicTripIdRouteRoute =
  layoutcustomPublicTripIdRouteRouteImport.update({
    id: '/(custom)/public/$tripId',
    path: '/public/$tripId',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutcustomBlogsBlogIdRouteRoute =
  layoutcustomBlogsBlogIdRouteRouteImport.update({
    id: '/(custom)/blogs/$blogId',
    path: '/blogs/$blogId',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutcustomPublicTripIdIndexRoute =
  layoutcustomPublicTripIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => layoutcustomPublicTripIdRouteRoute,
  } as any)
const layoutcustomBlogsBlogIdIndexRoute =
  layoutcustomBlogsBlogIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => layoutcustomBlogsBlogIdRouteRoute,
  } as any)
const layoutcustomTripsTripIdPlanRoute =
  layoutcustomTripsTripIdPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => layoutcustomTripsTripIdRouteRoute,
  } as any)
const layoutcustomTripsTripIdInfoRoute =
  layoutcustomTripsTripIdInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => layoutcustomTripsTripIdRouteRoute,
  } as any)
const layoutcustomTripsTripIdExpensesRoute =
  layoutcustomTripsTripIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => layoutcustomTripsTripIdRouteRoute,
  } as any)
const layoutcustomTripsTripIdChatRoute =
  layoutcustomTripsTripIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => layoutcustomTripsTripIdRouteRoute,
  } as any)
const layoutcustomBlogsBlogIdEditRoute =
  layoutcustomBlogsBlogIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => layoutcustomBlogsBlogIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof authSigninRoute
  '/sign-up/create-account': typeof authSignUpCreateAccountRoute
  '/sign-up/create-username': typeof authSignUpCreateUsernameRoute
  '/blogs': typeof layouthomeBlogsRoute
  '/dashboard': typeof layouthomeDashboardRoute
  '/expenses': typeof layouthomeExpensesRoute
  '/settings': typeof layouthomeSettingsRoute
  '/trips': typeof layouthomeTripsRoute
  '/blogs/$blogId': typeof layoutcustomBlogsBlogIdRouteRouteWithChildren
  '/public/$tripId': typeof layoutcustomPublicTripIdRouteRouteWithChildren
  '/trips/$tripId': typeof layoutcustomTripsTripIdRouteRouteWithChildren
  '/blogs/$blogId/edit': typeof layoutcustomBlogsBlogIdEditRoute
  '/trips/$tripId/chat': typeof layoutcustomTripsTripIdChatRoute
  '/trips/$tripId/expenses': typeof layoutcustomTripsTripIdExpensesRoute
  '/trips/$tripId/info': typeof layoutcustomTripsTripIdInfoRoute
  '/trips/$tripId/plan': typeof layoutcustomTripsTripIdPlanRoute
  '/blogs/$blogId/': typeof layoutcustomBlogsBlogIdIndexRoute
  '/public/$tripId/': typeof layoutcustomPublicTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof authSigninRoute
  '/sign-up/create-account': typeof authSignUpCreateAccountRoute
  '/sign-up/create-username': typeof authSignUpCreateUsernameRoute
  '/blogs': typeof layouthomeBlogsRoute
  '/dashboard': typeof layouthomeDashboardRoute
  '/expenses': typeof layouthomeExpensesRoute
  '/settings': typeof layouthomeSettingsRoute
  '/trips': typeof layouthomeTripsRoute
  '/trips/$tripId': typeof layoutcustomTripsTripIdRouteRouteWithChildren
  '/blogs/$blogId/edit': typeof layoutcustomBlogsBlogIdEditRoute
  '/trips/$tripId/chat': typeof layoutcustomTripsTripIdChatRoute
  '/trips/$tripId/expenses': typeof layoutcustomTripsTripIdExpensesRoute
  '/trips/$tripId/info': typeof layoutcustomTripsTripIdInfoRoute
  '/trips/$tripId/plan': typeof layoutcustomTripsTripIdPlanRoute
  '/blogs/$blogId': typeof layoutcustomBlogsBlogIdIndexRoute
  '/public/$tripId': typeof layoutcustomPublicTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(layout)': typeof layoutRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/(layout)/(home)': typeof layouthomeRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/sign-up/create-account': typeof authSignUpCreateAccountRoute
  '/(auth)/sign-up/create-username': typeof authSignUpCreateUsernameRoute
  '/(layout)/(home)/blogs': typeof layouthomeBlogsRoute
  '/(layout)/(home)/dashboard': typeof layouthomeDashboardRoute
  '/(layout)/(home)/expenses': typeof layouthomeExpensesRoute
  '/(layout)/(home)/settings': typeof layouthomeSettingsRoute
  '/(layout)/(home)/trips': typeof layouthomeTripsRoute
  '/(layout)/(custom)/blogs/$blogId': typeof layoutcustomBlogsBlogIdRouteRouteWithChildren
  '/(layout)/(custom)/public/$tripId': typeof layoutcustomPublicTripIdRouteRouteWithChildren
  '/(layout)/(custom)/trips/$tripId': typeof layoutcustomTripsTripIdRouteRouteWithChildren
  '/(layout)/(custom)/blogs/$blogId/edit': typeof layoutcustomBlogsBlogIdEditRoute
  '/(layout)/(custom)/trips/$tripId/chat': typeof layoutcustomTripsTripIdChatRoute
  '/(layout)/(custom)/trips/$tripId/expenses': typeof layoutcustomTripsTripIdExpensesRoute
  '/(layout)/(custom)/trips/$tripId/info': typeof layoutcustomTripsTripIdInfoRoute
  '/(layout)/(custom)/trips/$tripId/plan': typeof layoutcustomTripsTripIdPlanRoute
  '/(layout)/(custom)/blogs/$blogId/': typeof layoutcustomBlogsBlogIdIndexRoute
  '/(layout)/(custom)/public/$tripId/': typeof layoutcustomPublicTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/sign-up/create-account'
    | '/sign-up/create-username'
    | '/blogs'
    | '/dashboard'
    | '/expenses'
    | '/settings'
    | '/trips'
    | '/blogs/$blogId'
    | '/public/$tripId'
    | '/trips/$tripId'
    | '/blogs/$blogId/edit'
    | '/trips/$tripId/chat'
    | '/trips/$tripId/expenses'
    | '/trips/$tripId/info'
    | '/trips/$tripId/plan'
    | '/blogs/$blogId/'
    | '/public/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/sign-up/create-account'
    | '/sign-up/create-username'
    | '/blogs'
    | '/dashboard'
    | '/expenses'
    | '/settings'
    | '/trips'
    | '/trips/$tripId'
    | '/blogs/$blogId/edit'
    | '/trips/$tripId/chat'
    | '/trips/$tripId/expenses'
    | '/trips/$tripId/info'
    | '/trips/$tripId/plan'
    | '/blogs/$blogId'
    | '/public/$tripId'
  id:
    | '__root__'
    | '/'
    | '/(layout)'
    | '/onboarding'
    | '/(layout)/(home)'
    | '/(auth)/signin'
    | '/(auth)/sign-up/create-account'
    | '/(auth)/sign-up/create-username'
    | '/(layout)/(home)/blogs'
    | '/(layout)/(home)/dashboard'
    | '/(layout)/(home)/expenses'
    | '/(layout)/(home)/settings'
    | '/(layout)/(home)/trips'
    | '/(layout)/(custom)/blogs/$blogId'
    | '/(layout)/(custom)/public/$tripId'
    | '/(layout)/(custom)/trips/$tripId'
    | '/(layout)/(custom)/blogs/$blogId/edit'
    | '/(layout)/(custom)/trips/$tripId/chat'
    | '/(layout)/(custom)/trips/$tripId/expenses'
    | '/(layout)/(custom)/trips/$tripId/info'
    | '/(layout)/(custom)/trips/$tripId/plan'
    | '/(layout)/(custom)/blogs/$blogId/'
    | '/(layout)/(custom)/public/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  layoutRouteRoute: typeof layoutRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  authSigninRoute: typeof authSigninRoute
  authSignUpCreateAccountRoute: typeof authSignUpCreateAccountRoute
  authSignUpCreateUsernameRoute: typeof authSignUpCreateUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)': {
      id: '/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)/(home)': {
      id: '/(layout)/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layouthomeRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/(home)/trips': {
      id: '/(layout)/(home)/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof layouthomeTripsRouteImport
      parentRoute: typeof layouthomeRouteRoute
    }
    '/(layout)/(home)/settings': {
      id: '/(layout)/(home)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof layouthomeSettingsRouteImport
      parentRoute: typeof layouthomeRouteRoute
    }
    '/(layout)/(home)/expenses': {
      id: '/(layout)/(home)/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof layouthomeExpensesRouteImport
      parentRoute: typeof layouthomeRouteRoute
    }
    '/(layout)/(home)/dashboard': {
      id: '/(layout)/(home)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof layouthomeDashboardRouteImport
      parentRoute: typeof layouthomeRouteRoute
    }
    '/(layout)/(home)/blogs': {
      id: '/(layout)/(home)/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof layouthomeBlogsRouteImport
      parentRoute: typeof layouthomeRouteRoute
    }
    '/(auth)/sign-up/create-username': {
      id: '/(auth)/sign-up/create-username'
      path: '/sign-up/create-username'
      fullPath: '/sign-up/create-username'
      preLoaderRoute: typeof authSignUpCreateUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up/create-account': {
      id: '/(auth)/sign-up/create-account'
      path: '/sign-up/create-account'
      fullPath: '/sign-up/create-account'
      preLoaderRoute: typeof authSignUpCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)/(custom)/trips/$tripId': {
      id: '/(layout)/(custom)/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof layoutcustomTripsTripIdRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/(custom)/public/$tripId': {
      id: '/(layout)/(custom)/public/$tripId'
      path: '/public/$tripId'
      fullPath: '/public/$tripId'
      preLoaderRoute: typeof layoutcustomPublicTripIdRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/(custom)/blogs/$blogId': {
      id: '/(layout)/(custom)/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof layoutcustomBlogsBlogIdRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/(custom)/public/$tripId/': {
      id: '/(layout)/(custom)/public/$tripId/'
      path: '/'
      fullPath: '/public/$tripId/'
      preLoaderRoute: typeof layoutcustomPublicTripIdIndexRouteImport
      parentRoute: typeof layoutcustomPublicTripIdRouteRoute
    }
    '/(layout)/(custom)/blogs/$blogId/': {
      id: '/(layout)/(custom)/blogs/$blogId/'
      path: '/'
      fullPath: '/blogs/$blogId/'
      preLoaderRoute: typeof layoutcustomBlogsBlogIdIndexRouteImport
      parentRoute: typeof layoutcustomBlogsBlogIdRouteRoute
    }
    '/(layout)/(custom)/trips/$tripId/plan': {
      id: '/(layout)/(custom)/trips/$tripId/plan'
      path: '/plan'
      fullPath: '/trips/$tripId/plan'
      preLoaderRoute: typeof layoutcustomTripsTripIdPlanRouteImport
      parentRoute: typeof layoutcustomTripsTripIdRouteRoute
    }
    '/(layout)/(custom)/trips/$tripId/info': {
      id: '/(layout)/(custom)/trips/$tripId/info'
      path: '/info'
      fullPath: '/trips/$tripId/info'
      preLoaderRoute: typeof layoutcustomTripsTripIdInfoRouteImport
      parentRoute: typeof layoutcustomTripsTripIdRouteRoute
    }
    '/(layout)/(custom)/trips/$tripId/expenses': {
      id: '/(layout)/(custom)/trips/$tripId/expenses'
      path: '/expenses'
      fullPath: '/trips/$tripId/expenses'
      preLoaderRoute: typeof layoutcustomTripsTripIdExpensesRouteImport
      parentRoute: typeof layoutcustomTripsTripIdRouteRoute
    }
    '/(layout)/(custom)/trips/$tripId/chat': {
      id: '/(layout)/(custom)/trips/$tripId/chat'
      path: '/chat'
      fullPath: '/trips/$tripId/chat'
      preLoaderRoute: typeof layoutcustomTripsTripIdChatRouteImport
      parentRoute: typeof layoutcustomTripsTripIdRouteRoute
    }
    '/(layout)/(custom)/blogs/$blogId/edit': {
      id: '/(layout)/(custom)/blogs/$blogId/edit'
      path: '/edit'
      fullPath: '/blogs/$blogId/edit'
      preLoaderRoute: typeof layoutcustomBlogsBlogIdEditRouteImport
      parentRoute: typeof layoutcustomBlogsBlogIdRouteRoute
    }
  }
}

interface layouthomeRouteRouteChildren {
  layouthomeBlogsRoute: typeof layouthomeBlogsRoute
  layouthomeDashboardRoute: typeof layouthomeDashboardRoute
  layouthomeExpensesRoute: typeof layouthomeExpensesRoute
  layouthomeSettingsRoute: typeof layouthomeSettingsRoute
  layouthomeTripsRoute: typeof layouthomeTripsRoute
}

const layouthomeRouteRouteChildren: layouthomeRouteRouteChildren = {
  layouthomeBlogsRoute: layouthomeBlogsRoute,
  layouthomeDashboardRoute: layouthomeDashboardRoute,
  layouthomeExpensesRoute: layouthomeExpensesRoute,
  layouthomeSettingsRoute: layouthomeSettingsRoute,
  layouthomeTripsRoute: layouthomeTripsRoute,
}

const layouthomeRouteRouteWithChildren = layouthomeRouteRoute._addFileChildren(
  layouthomeRouteRouteChildren,
)

interface layoutcustomBlogsBlogIdRouteRouteChildren {
  layoutcustomBlogsBlogIdEditRoute: typeof layoutcustomBlogsBlogIdEditRoute
  layoutcustomBlogsBlogIdIndexRoute: typeof layoutcustomBlogsBlogIdIndexRoute
}

const layoutcustomBlogsBlogIdRouteRouteChildren: layoutcustomBlogsBlogIdRouteRouteChildren =
  {
    layoutcustomBlogsBlogIdEditRoute: layoutcustomBlogsBlogIdEditRoute,
    layoutcustomBlogsBlogIdIndexRoute: layoutcustomBlogsBlogIdIndexRoute,
  }

const layoutcustomBlogsBlogIdRouteRouteWithChildren =
  layoutcustomBlogsBlogIdRouteRoute._addFileChildren(
    layoutcustomBlogsBlogIdRouteRouteChildren,
  )

interface layoutcustomPublicTripIdRouteRouteChildren {
  layoutcustomPublicTripIdIndexRoute: typeof layoutcustomPublicTripIdIndexRoute
}

const layoutcustomPublicTripIdRouteRouteChildren: layoutcustomPublicTripIdRouteRouteChildren =
  {
    layoutcustomPublicTripIdIndexRoute: layoutcustomPublicTripIdIndexRoute,
  }

const layoutcustomPublicTripIdRouteRouteWithChildren =
  layoutcustomPublicTripIdRouteRoute._addFileChildren(
    layoutcustomPublicTripIdRouteRouteChildren,
  )

interface layoutcustomTripsTripIdRouteRouteChildren {
  layoutcustomTripsTripIdChatRoute: typeof layoutcustomTripsTripIdChatRoute
  layoutcustomTripsTripIdExpensesRoute: typeof layoutcustomTripsTripIdExpensesRoute
  layoutcustomTripsTripIdInfoRoute: typeof layoutcustomTripsTripIdInfoRoute
  layoutcustomTripsTripIdPlanRoute: typeof layoutcustomTripsTripIdPlanRoute
}

const layoutcustomTripsTripIdRouteRouteChildren: layoutcustomTripsTripIdRouteRouteChildren =
  {
    layoutcustomTripsTripIdChatRoute: layoutcustomTripsTripIdChatRoute,
    layoutcustomTripsTripIdExpensesRoute: layoutcustomTripsTripIdExpensesRoute,
    layoutcustomTripsTripIdInfoRoute: layoutcustomTripsTripIdInfoRoute,
    layoutcustomTripsTripIdPlanRoute: layoutcustomTripsTripIdPlanRoute,
  }

const layoutcustomTripsTripIdRouteRouteWithChildren =
  layoutcustomTripsTripIdRouteRoute._addFileChildren(
    layoutcustomTripsTripIdRouteRouteChildren,
  )

interface layoutRouteRouteChildren {
  layouthomeRouteRoute: typeof layouthomeRouteRouteWithChildren
  layoutcustomBlogsBlogIdRouteRoute: typeof layoutcustomBlogsBlogIdRouteRouteWithChildren
  layoutcustomPublicTripIdRouteRoute: typeof layoutcustomPublicTripIdRouteRouteWithChildren
  layoutcustomTripsTripIdRouteRoute: typeof layoutcustomTripsTripIdRouteRouteWithChildren
}

const layoutRouteRouteChildren: layoutRouteRouteChildren = {
  layouthomeRouteRoute: layouthomeRouteRouteWithChildren,
  layoutcustomBlogsBlogIdRouteRoute:
    layoutcustomBlogsBlogIdRouteRouteWithChildren,
  layoutcustomPublicTripIdRouteRoute:
    layoutcustomPublicTripIdRouteRouteWithChildren,
  layoutcustomTripsTripIdRouteRoute:
    layoutcustomTripsTripIdRouteRouteWithChildren,
}

const layoutRouteRouteWithChildren = layoutRouteRoute._addFileChildren(
  layoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  layoutRouteRoute: layoutRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  authSigninRoute: authSigninRoute,
  authSignUpCreateAccountRoute: authSignUpCreateAccountRoute,
  authSignUpCreateUsernameRoute: authSignUpCreateUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
